### ISSUE TITLE
Move `myft-digest-promo` into components

### ISSUE THREAD

**Issue by benbarnett** [Financial-Times/n-myft-ui#162]
- [x] Move contents of `myft-digest-promo`  into `components/digest-promo`
- [x] Make surrogate entry points to load the files from the new location, so consumer apps don't break

**Comment by fenglish** [comment]
myft-digest-promo is only used on stream page at the moment, so I just changed the entry points in next-stream-page instead of `Make surrogate entry points to load the files from the new location...`.
https://github.com/Financial-Times/next-stream-page/pull/1998

**Comment by fenglish** [comment]
#170

**Comment by dan-searle** [comment]
We had decided on the surrogate entry point approach as a way of avoiding lots of major version bumps of n-myft-ui and the apps that consume.

**Comment by benbarnett** [comment]
@dan-searle sorry yes we had, but @fenglish noticed that this one was only used in a single place and so just made sense to clean this one up in one hit. Has resulted in a new major though.

**Comment by benbarnett** [comment]
Ignore the above, we are sticking with the surrogate approach and will do a 'one hit major' once all the components have been moved
