### ISSUE TITLE
Move `n-myft-ui/myft/ui/myft-buttons/collections` into its own component

### ISSUE THREAD

**Issue by benbarnett** [Financial-Times/n-myft-ui#164]
- [ ] Move contents of `n-myft-ui/myft/ui/myft-buttons/collections`  into `components/collections`
- [ ] Make surrogate entry points to load the files from the new location, so consumer apps don't break

**Comment by alexandercurtis** [comment]
On closer inspection, this doesn't make sense. This file is one of a group of files that handle the state and activity of all the follow buttons (etc) on the page. I'm examining whether this functionality could be moved to a better place, and/or otherwise made more obvious/explicit/simpler.

**Comment by benbarnett** [comment]
Closed in favour of #190 and #189
