### ISSUE TITLE
Move template files from templates directory into components

### ISSUE THREAD

**Issue by benbarnett** [Financial-Times/n-myft-ui#198]
So that the templates are stored directly against the components that use them.

**Comment by chee** [comment]
these need moved (with a pass-thru), then updated in the apps that use them, and then deleted:
- [ ] myft/templates/save-for-later.html
- [ ] myft/templates/unsave-for-later.html

these need updated in the apps that use them, and then deleted:
- [ ] myft/templates/follow.html


Also can we do the same thing with save/unsave that we did to follow/unfollow (make them the same component with an option?)

**Comment by chee** [comment]
Also can we do the same thing with save/unsave that we did to follow/unfollow (make them the same component with an option?)

**Comment by chee** [comment]
# follow button uses

https://github.com/search?q=org%3Afinancial-times+myft%2Ftemplates%2Ffollow&type=Code

## within n-myft-ui
- [ ] [collections.html](https://github.com/Financial-Times/n-myft-ui/blob/5c26a3d62e6caa6f98de1bba9236aeef89dc29b0/components/collections/collections.html)
- [ ] [digest-on-follow.html](https://github.com/Financial-Times/n-myft-ui/blob/4058911ce19ed97e9e3e19baca752a4981e82400/demos/templates/digest-on-follow.html)
- [ ] [README.md](https://github.com/Financial-Times/n-myft-ui/blob/4058911ce19ed97e9e3e19baca752a4981e82400/myft/README.md)
- [ ] [demo.html](https://github.com/Financial-Times/n-myft-ui/blob/4058911ce19ed97e9e3e19baca752a4981e82400/demos/templates/demo.html)
- [ ] [app.js](https://github.com/Financial-Times/n-myft-ui/blob/a7d33cc683308c2a4cc8e839a7ab90423893e82e/demos/app.js)

## elsewhere
- [ ] [n-topic-card](https://github.com/Financial-Times/n-topic-card)
- [ ] [next-front-page](https://github.com/Financial-Times/next-front-page)
- [ ] [next-article](https://github.com/Financial-Times/next-article)
- [ ] [next-graphics-page](https://github.com/Financial-Times/next-article)
- [ ] [next-myft-page](https://github.com/Financial-Times/next-myft-page)
- [ ] [n-concept](https://github.com/Financial-Times/n-concept)
- [ ] [next-stream-page](https://github.com/Financial-Times/next-stream-page)

**Comment by chee** [comment]
i'm going to do a PR updating the uses from within n-myft-ui.
