### ISSUE TITLE
Follow buttons on MyFT logged in front page slice display no text

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-myft-ui#412]
We have an issue on the Page Kit version of the front page app whereby the topic follow buttons displayed within the `n-topic-card` component do not have any text. All other state and functionality appears to work as expected:

<img width="1000" alt="Screenshot 2020-02-04 at 12 55 07" src="https://user-images.githubusercontent.com/271645/73746823-02e7fa80-474e-11ea-9ef3-8040be9b38e8.png">

The topic card component does not render the topic follow buttons with any text. This is true for both the live site and our Page Kit branch. Please note that the button template is intended to truncate whitespace (the `~`): https://github.com/Financial-Times/n-myft-ui/blob/66c584a9769cae0e76bbb58753a1dbc793446b3d/components/follow-button/follow-button.html

When we dug into this we found that the button text is actually being set by this script, within a condition: https://github.com/Financial-Times/n-myft-ui/blob/66c584a9769cae0e76bbb58753a1dbc793446b3d/myft-common/index.js

The difference between the live site and our Page Kit branch is that the `text` variable. On the live site this is being set to non-empty string (literally the _whitespace_ in the HTML) but it is an empty string on our Page Kit branch:

<img width="1280" alt="Screenshot 2020-02-04 at 12 50 07" src="https://user-images.githubusercontent.com/271645/73752359-be159100-4758-11ea-863c-a55a91d95a9e.png">

We're not sure what to do about this and we would like your help. I've marked this as a bug because even though the feature is currently working on the live site it's definitely not working in the manner intended.

**Comment by i-like-robots** [comment]
As far as I can tell in order to get this working again we need to do two things:

1. Update the front page integration with the topic card to include 3 additional properties; `name`, `setFollowButtonStateToSelected` and `cacheablePersonalisedUrl`:

    ```hbs
    {{> n-topic-card/templates/concept flags=@root.flags conceptId=id items=latestContent name=prefLabel setFollowButtonStateToSelected=true cacheablePersonalisedUrl=true}}
   ```

2. Update this condition in the template to use `{{#unless}}` due to all _falsy_ flags being filtered out of flags data in Page Kit: https://github.com/Financial-Times/n-myft-ui/blob/66c584a9769cae0e76bbb58753a1dbc793446b3d/components/follow-button/follow-button.html#L145-L151

**Comment by jenniferemshepherd** [comment]
so pleased we now know why. V happy for these changes to be implemented 🙏

**Comment by jenniferemshepherd** [comment]
Why are you uncomfortable about `cacheablePersonalisedUrl=true`?

**Comment by i-like-robots** [comment]
> Why are you uncomfortable about cacheablePersonalisedUrl=true?

I think this may be a concern of the MyFT page that has leaked out. We're rendering on the front page and on the client-side, we're not caching nor have personalised URLs.

**Comment by robsquires** [comment]
Finding out we can remove the ABtest code altogether.

**Comment by robsquires** [comment]
Confirmed AB test code can be removed...content disco team can do this.

Re. `cacheablePersonalisedUrl`. We can take on a timeboxed task to try and remove the need to set this in the frontpage. If we can't, is it ok to proceed with the migration with it set? < We're fleshing out some work which would remove handlebars from the myft slot all all together + would likely resolve it then

**Comment by i-like-robots** [comment]
I think it's fine to proceed with `cacheablePersonalisedUrl`, happy to chalk it up as "some legacy thing" that will be resolved in due course.
